// COPA Internationalization
// Centralized copy for easy language swapping

export type Language = 'en' | 'de'

export const translations = {
  en: {
    // Common
    common: {
      login: 'Log in',
      logout: 'Log out',
      register: 'Register',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      search: 'Search',
      loading: 'Loading...',
      settings: 'Settings',
      profile: 'Profile',
      dashboard: 'Dashboard',
      back: 'Back',
      next: 'Next',
      submit: 'Submit',
      close: 'Close',
    },
    // Landing page
    landing: {
      hero: {
        title: 'AI-Powered Learning, Personalised for Every Student',
        subtitle: 'COPA helps teachers create differentiated lessons and inclusive materials while keeping student data safe and secure.',
        cta: 'Log in',
        secondaryCta: 'Book a Demo',
      },
      forTeachers: {
        title: 'For Teachers',
        points: [
          'Create differentiated tasks for all learning levels',
          'Save hours with AI-generated lesson plans',
          'Scan materials for bias and inclusion issues',
        ],
      },
      forStudents: {
        title: 'For Students',
        points: [
          'Learn your way: Read, Play, or Watch',
          'Personalised activities based on your progress',
          'Track achievements and earn rewards',
        ],
      },
      forSchools: {
        title: 'For Schools & LMS',
        points: [
          'API-first architecture for easy integration',
          'Federated data model: your data stays with you',
          'EU-compliant and GDPR-ready',
        ],
      },
      howItWorks: {
        title: 'How It Works',
        steps: [
          { title: 'Connect', description: 'Link COPA to your school system' },
          { title: 'Create', description: 'Build lessons with AI assistance' },
          { title: 'Personalise', description: 'Students learn in their preferred style' },
        ],
      },
    },
    // Auth
    auth: {
      selectRole: 'I am a...',
      teacher: 'Teacher',
      student: 'Student',
      selectOrganisation: 'Select your organisation',
      organisationCode: 'Organisation code',
      addOrganisation: 'Add organisation code',
      email: 'Email address',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
    },
    // Teacher
    teacher: {
      nav: {
        dashboard: 'Dashboard',
        classes: 'Classes',
        lessonBuilder: 'Lesson Builder',
        biasScanner: 'Bias Scanner',
        students: 'Students',
        analytics: 'Analytics',
        settings: 'Settings',
        fairnessLab: 'Fairness Lab',
      },
      dashboard: {
        welcome: 'Welcome back',
        todayClasses: "Today's Classes",
        differentiationOverview: 'Differentiation Overview',
        inclusionRadar: 'Inclusion Radar',
        quickActions: 'Quick Actions',
        createLesson: 'Create Lesson',
        scanMaterial: 'Scan Material',
        assignPath: 'Assign Adaptive Path',
        dataPrivacy: "Your students' detailed data stays on this school server. COPA only uses anonymised patterns.",
      },
      lessonBuilder: {
        title: 'Lesson Builder',
        class: 'Class',
        subject: 'Subject',
        topic: 'Topic / Title',
        objective: 'Learning Objective',
        material: 'Base Material',
        uploadMaterial: 'Paste or upload material',
        differentiationPrefs: 'Differentiation Preferences',
        createLevels: 'Create 3 levels (struggling / on-track / advanced)',
        languageLearners: 'Include support for language learners',
        preview: 'AI Output Preview',
        overview: 'Overview',
        struggling: 'For Struggling Learners',
        onTrack: 'For On-track Learners',
        advanced: 'For Advanced Learners',
        generatedByAI: 'Generated by AI',
        whyThis: 'Why this?',
        saveAssign: 'Save & Assign Later',
        runBiasScan: 'Run Bias Scan on This Lesson',
      },
      biasScanner: {
        title: 'Bias & Inclusion Scanner',
        inputLabel: 'Teaching Material',
        scanButton: 'Scan for Bias & Inclusion Issues',
        results: 'Scan Results',
        noIssues: 'No issues found. Your material looks inclusive!',
        issuesFound: 'issues found',
        categories: {
          gender: 'Gender & Stereotypes',
          culture: 'Cultural Assumptions',
          socioeconomic: 'Socio-economic Bias',
          ableism: 'Ableism / Neurodiversity',
        },
        replace: 'Replace in Text',
        severity: {
          low: 'Low',
          medium: 'Medium',
          high: 'High',
        },
      },
      classes: {
        title: 'Classes',
        grade: 'Grade',
        students: 'Students',
        nextLesson: 'Next Lesson',
        tabs: {
          students: 'Students',
          learningModes: 'Learning Modes',
          inclusion: 'Inclusion',
        },
        assignActivities: 'Assign Tailored Activities',
        lastActivity: 'Last Activity',
        performance: 'Performance',
      },
      students: {
        overview: 'Overview',
        learningPlan: 'Learning Plan',
        materials: 'Materials',
        recentQuiz: 'Recent Quiz Score',
        activityLevel: 'Activity Level',
        recommendedMode: 'Recommended Mode',
        teacherNotes: 'Teacher Notes',
        addActivity: 'Add New Activity',
        switchMode: 'Switch Mode Emphasis',
        biasScanStatus: 'Bias Scan Status',
      },
    },
    // Student
    student: {
      nav: {
        dashboard: 'Dashboard',
        activities: 'Activities',
        progress: 'Progress',
        preferences: 'Preferences',
        settings: 'Settings',
      },
      dashboard: {
        greeting: 'Hey',
        progress: 'Your Progress',
        recommendedMode: 'You learn best with',
        recommendation: 'Based on your recent quizzes and what you clicked most, we recommend these learning activities.',
        currentTopic: 'Current Topic',
        quickTest: 'Quick Test',
        modes: {
          read: 'Read',
          play: 'Play',
          watch: 'Watch',
        },
      },
      preferences: {
        title: 'Learning Preferences',
        systemRecommendation: 'System Recommendation',
        yourChoice: 'Your Choice',
        confirm: 'Confirm Selection',
        override: 'Use My Preference',
        explanation: 'Your teacher can see these preferences and adjust your learning plan.',
      },
    },
    // Organisation
    org: {
      settings: {
        title: 'Organisation Settings',
        name: 'Organisation Name',
        id: 'Organisation ID',
        apiKeys: 'API Keys',
        webhooks: 'Webhook URLs',
        copyKey: 'Copy',
        integrations: 'Integrations',
        lmsIntegration: 'Allow LMS Integration',
        thirdPartyContent: 'Allow 3rd Party Content Providers',
        federatedLearning: 'Enable Federated Learning Updates',
        dataPrivacy: 'Data stays in your organisation. Only aggregated, anonymised model updates are sent to COPA servers.',
        federatedCard: {
          title: 'Federated Learning',
          sendSignals: 'Send anonymised learning signals',
          participateModel: 'Participate in model improvement',
          modelVersion: 'Latest model version used in this org',
        },
      },
    },
    // Fairness Lab
    fairnessLab: {
      title: 'Fairness Lab',
      description: 'Use this lab to verify that COPA\'s suggestions do not change based on sensitive attributes alone.',
      profileA: 'Student Profile A',
      profileB: 'Student Profile B',
      name: 'Display Name',
      attribute: 'Differing Attribute',
      skills: 'Skills (identical)',
      compare: 'Compare AI Suggestions',
      results: 'AI Suggestion Comparison',
      identical: 'The AI suggestions are identical, demonstrating fair treatment.',
    },
  },
  de: {
    // Common
    common: {
      login: 'Anmelden',
      logout: 'Abmelden',
      register: 'Registrieren',
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      create: 'Erstellen',
      search: 'Suchen',
      loading: 'Wird geladen...',
      settings: 'Einstellungen',
      profile: 'Profil',
      dashboard: 'Dashboard',
      back: 'Zurück',
      next: 'Weiter',
      submit: 'Absenden',
      close: 'Schließen',
    },
    // Landing page
    landing: {
      hero: {
        title: 'KI-gestütztes Lernen, personalisiert für jeden Schüler',
        subtitle: 'COPA hilft Lehrkräften, differenzierte Unterrichtsstunden und inklusive Materialien zu erstellen – bei voller Datensicherheit.',
        cta: 'Anmelden',
        secondaryCta: 'Demo buchen',
      },
      forTeachers: {
        title: 'Für Lehrkräfte',
        points: [
          'Differenzierte Aufgaben für alle Lernniveaus erstellen',
          'Stunden sparen mit KI-generierten Unterrichtsplänen',
          'Materialien auf Vorurteile und Inklusion prüfen',
        ],
      },
      forStudents: {
        title: 'Für Schüler:innen',
        points: [
          'Lerne auf deine Art: Lesen, Spielen oder Schauen',
          'Personalisierte Aktivitäten basierend auf deinem Fortschritt',
          'Verfolge Erfolge und sammle Belohnungen',
        ],
      },
      forSchools: {
        title: 'Für Schulen & LMS',
        points: [
          'API-first-Architektur für einfache Integration',
          'Föderiertes Datenmodell: Ihre Daten bleiben bei Ihnen',
          'EU-konform und DSGVO-bereit',
        ],
      },
      howItWorks: {
        title: 'So funktioniert es',
        steps: [
          { title: 'Verbinden', description: 'COPA mit Ihrem Schulsystem verknüpfen' },
          { title: 'Erstellen', description: 'Unterricht mit KI-Unterstützung gestalten' },
          { title: 'Personalisieren', description: 'Schüler lernen in ihrem bevorzugten Stil' },
        ],
      },
    },
    // Auth
    auth: {
      selectRole: 'Ich bin...',
      teacher: 'Lehrkraft',
      student: 'Schüler:in',
      selectOrganisation: 'Organisation auswählen',
      organisationCode: 'Organisationscode',
      addOrganisation: 'Organisationscode hinzufügen',
      email: 'E-Mail-Adresse',
      password: 'Passwort',
      forgotPassword: 'Passwort vergessen?',
      noAccount: 'Noch kein Konto?',
      hasAccount: 'Bereits ein Konto?',
    },
    // Teacher (abbreviated for brevity - full translations would follow same pattern)
    teacher: {
      nav: {
        dashboard: 'Dashboard',
        classes: 'Klassen',
        lessonBuilder: 'Unterrichtsplaner',
        biasScanner: 'Bias-Scanner',
        students: 'Schüler:innen',
        analytics: 'Analysen',
        settings: 'Einstellungen',
        fairnessLab: 'Fairness-Labor',
      },
      dashboard: {
        welcome: 'Willkommen zurück',
        todayClasses: 'Heutige Klassen',
        differentiationOverview: 'Differenzierungsübersicht',
        inclusionRadar: 'Inklusions-Radar',
        quickActions: 'Schnellaktionen',
        createLesson: 'Unterricht erstellen',
        scanMaterial: 'Material scannen',
        assignPath: 'Adaptiven Pfad zuweisen',
        dataPrivacy: 'Die detaillierten Daten Ihrer Schüler:innen bleiben auf diesem Schulserver. COPA verwendet nur anonymisierte Muster.',
      },
      lessonBuilder: {
        title: 'Unterrichtsplaner',
        class: 'Klasse',
        subject: 'Fach',
        topic: 'Thema / Titel',
        objective: 'Lernziel',
        material: 'Basismaterial',
        uploadMaterial: 'Material einfügen oder hochladen',
        differentiationPrefs: 'Differenzierungseinstellungen',
        createLevels: '3 Niveaus erstellen (Förderung / Standard / Erweiterung)',
        languageLearners: 'Unterstützung für Sprachlernende einbeziehen',
        preview: 'KI-Ausgabe Vorschau',
        overview: 'Übersicht',
        struggling: 'Für Förderbedarf',
        onTrack: 'Für Standardniveau',
        advanced: 'Für Erweiterungsniveau',
        generatedByAI: 'Von KI generiert',
        whyThis: 'Warum das?',
        saveAssign: 'Speichern & Später zuweisen',
        runBiasScan: 'Bias-Scan durchführen',
      },
      biasScanner: {
        title: 'Bias- & Inklusions-Scanner',
        inputLabel: 'Unterrichtsmaterial',
        scanButton: 'Auf Vorurteile & Inklusionsprobleme scannen',
        results: 'Scan-Ergebnisse',
        noIssues: 'Keine Probleme gefunden. Ihr Material ist inklusiv!',
        issuesFound: 'Probleme gefunden',
        categories: {
          gender: 'Geschlecht & Stereotypen',
          culture: 'Kulturelle Annahmen',
          socioeconomic: 'Sozioökonomische Vorurteile',
          ableism: 'Ableismus / Neurodiversität',
        },
        replace: 'Im Text ersetzen',
        severity: {
          low: 'Niedrig',
          medium: 'Mittel',
          high: 'Hoch',
        },
      },
      classes: {
        title: 'Klassen',
        grade: 'Stufe',
        students: 'Schüler:innen',
        nextLesson: 'Nächste Stunde',
        tabs: {
          students: 'Schüler:innen',
          learningModes: 'Lernmodi',
          inclusion: 'Inklusion',
        },
        assignActivities: 'Angepasste Aktivitäten zuweisen',
        lastActivity: 'Letzte Aktivität',
        performance: 'Leistung',
      },
      students: {
        overview: 'Übersicht',
        learningPlan: 'Lernplan',
        materials: 'Materialien',
        recentQuiz: 'Letzter Quiz-Score',
        activityLevel: 'Aktivitätslevel',
        recommendedMode: 'Empfohlener Modus',
        teacherNotes: 'Lehrer-Notizen',
        addActivity: 'Neue Aktivität hinzufügen',
        switchMode: 'Modus-Schwerpunkt wechseln',
        biasScanStatus: 'Bias-Scan-Status',
      },
    },
    // Student
    student: {
      nav: {
        dashboard: 'Dashboard',
        activities: 'Aktivitäten',
        progress: 'Fortschritt',
        preferences: 'Einstellungen',
        settings: 'Einstellungen',
      },
      dashboard: {
        greeting: 'Hallo',
        progress: 'Dein Fortschritt',
        recommendedMode: 'Du lernst am besten mit',
        recommendation: 'Basierend auf deinen letzten Tests und was du am meisten geklickt hast, empfehlen wir diese Lernaktivitäten.',
        currentTopic: 'Aktuelles Thema',
        quickTest: 'Schnelltest',
        modes: {
          read: 'Lesen',
          play: 'Spielen',
          watch: 'Schauen',
        },
      },
      preferences: {
        title: 'Lerneinstellungen',
        systemRecommendation: 'Systemempfehlung',
        yourChoice: 'Deine Auswahl',
        confirm: 'Auswahl bestätigen',
        override: 'Meine Einstellung verwenden',
        explanation: 'Deine Lehrkraft kann diese Einstellungen sehen und deinen Lernplan anpassen.',
      },
    },
    // Organisation
    org: {
      settings: {
        title: 'Organisationseinstellungen',
        name: 'Organisationsname',
        id: 'Organisations-ID',
        apiKeys: 'API-Schlüssel',
        webhooks: 'Webhook-URLs',
        copyKey: 'Kopieren',
        integrations: 'Integrationen',
        lmsIntegration: 'LMS-Integration erlauben',
        thirdPartyContent: 'Drittanbieter-Inhalte erlauben',
        federatedLearning: 'Föderierte Lernaktualisierungen aktivieren',
        dataPrivacy: 'Daten bleiben in Ihrer Organisation. Nur aggregierte, anonymisierte Modellaktualisierungen werden an COPA-Server gesendet.',
        federatedCard: {
          title: 'Föderiertes Lernen',
          sendSignals: 'Anonymisierte Lernsignale senden',
          participateModel: 'An Modellverbesserung teilnehmen',
          modelVersion: 'Neueste Modellversion in dieser Organisation',
        },
      },
    },
    // Fairness Lab
    fairnessLab: {
      title: 'Fairness-Labor',
      description: 'Verwenden Sie dieses Labor, um zu überprüfen, dass die Vorschläge von COPA sich nicht aufgrund sensibler Attribute ändern.',
      profileA: 'Schülerprofil A',
      profileB: 'Schülerprofil B',
      name: 'Anzeigename',
      attribute: 'Unterscheidendes Merkmal',
      skills: 'Fähigkeiten (identisch)',
      compare: 'KI-Vorschläge vergleichen',
      results: 'KI-Vorschlagsvergleich',
      identical: 'Die KI-Vorschläge sind identisch, was eine faire Behandlung zeigt.',
    },
  },
} as const

export type Translations = typeof translations.en

export function useTranslations(lang: Language = 'en'): Translations {
  return translations[lang]
}

// Date/time formatting for Europe
export function formatDate(date: Date | string, lang: Language = 'en'): string {
  const d = typeof date === 'string' ? new Date(date) : date
  return d.toLocaleDateString(lang === 'de' ? 'de-DE' : 'en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  })
}

export function formatTime(date: Date | string, lang: Language = 'en'): string {
  const d = typeof date === 'string' ? new Date(date) : date
  return d.toLocaleTimeString(lang === 'de' ? 'de-DE' : 'en-GB', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  })
}

export function formatDateTime(date: Date | string, lang: Language = 'en'): string {
  return `${formatDate(date, lang)}, ${formatTime(date, lang)}`
}
